import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./Components/Header/Header";
import { Toaster } from "react-hot-toast";
import AuthProvider from "./Components/AuthProvider";
import { Suspense } from "react";
import loading from "./loading"
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Rooms in Gokhalenagar",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <Toaster />
          <Header />
          
         
            <div className="min-h-screen">
            <Suspense fallback={<loading />}>
              {children}
          </Suspense>
          </div>
        </AuthProvider>
      </body>
    </html>
  );
}
